# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=False)),
                ('qty', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
